bash /home/estorrs/dance/dance/scripts/1.filter_bams.sh /diskmnt/Projects/Users/estorrs/1000-genomes/GRCh37/positions.chr.all.coding.sorted.02maf.10000sampled.sorted.snps.bed /diskmnt/Projects/Users/estorrs/data/ancestry/MM/bams/56203-1.bam /diskmnt/Projects/Users/estorrs/data/ancestry/MM/filtered_bams/56203-1.1000-genome_filtered.bam &
bash /home/estorrs/dance/dance/scripts/1.filter_bams.sh /diskmnt/Projects/Users/estorrs/1000-genomes/GRCh37/positions.chr.all.coding.sorted.02maf.10000sampled.sorted.snps.bed /diskmnt/Projects/Users/estorrs/data/ancestry/MM/bams/56203-2.bam /diskmnt/Projects/Users/estorrs/data/ancestry/MM/filtered_bams/56203-2.1000-genome_filtered.bam &
bash /home/estorrs/dance/dance/scripts/1.filter_bams.sh /diskmnt/Projects/Users/estorrs/1000-genomes/GRCh37/positions.chr.all.coding.sorted.02maf.10000sampled.sorted.snps.bed /diskmnt/Projects/Users/estorrs/data/ancestry/MM/bams/56203-N.bam /diskmnt/Projects/Users/estorrs/data/ancestry/MM/filtered_bams/56203-N.1000-genome_filtered.bam &
bash /home/estorrs/dance/dance/scripts/1.filter_bams.sh /diskmnt/Projects/Users/estorrs/1000-genomes/GRCh37/positions.chr.all.coding.sorted.02maf.10000sampled.sorted.snps.bed /diskmnt/Projects/Users/estorrs/data/ancestry/MM/bams/58408-1.bam /diskmnt/Projects/Users/estorrs/data/ancestry/MM/filtered_bams/58408-1.1000-genome_filtered.bam &
bash /home/estorrs/dance/dance/scripts/1.filter_bams.sh /diskmnt/Projects/Users/estorrs/1000-genomes/GRCh37/positions.chr.all.coding.sorted.02maf.10000sampled.sorted.snps.bed /diskmnt/Projects/Users/estorrs/data/ancestry/MM/bams/58408-2.bam /diskmnt/Projects/Users/estorrs/data/ancestry/MM/filtered_bams/58408-2.1000-genome_filtered.bam &
bash /home/estorrs/dance/dance/scripts/1.filter_bams.sh /diskmnt/Projects/Users/estorrs/1000-genomes/GRCh37/positions.chr.all.coding.sorted.02maf.10000sampled.sorted.snps.bed /diskmnt/Projects/Users/estorrs/data/ancestry/MM/bams/58408-N.bam /diskmnt/Projects/Users/estorrs/data/ancestry/MM/filtered_bams/58408-N.1000-genome_filtered.bam &
bash /home/estorrs/dance/dance/scripts/1.filter_bams.sh /diskmnt/Projects/Users/estorrs/1000-genomes/GRCh37/positions.chr.all.coding.sorted.02maf.10000sampled.sorted.snps.bed /diskmnt/Projects/Users/estorrs/data/ancestry/MM/bams/59114-2.bam /diskmnt/Projects/Users/estorrs/data/ancestry/MM/filtered_bams/59114-2.1000-genome_filtered.bam &
bash /home/estorrs/dance/dance/scripts/1.filter_bams.sh /diskmnt/Projects/Users/estorrs/1000-genomes/GRCh37/positions.chr.all.coding.sorted.02maf.10000sampled.sorted.snps.bed /diskmnt/Projects/Users/estorrs/data/ancestry/MM/bams/59114-3.bam /diskmnt/Projects/Users/estorrs/data/ancestry/MM/filtered_bams/59114-3.1000-genome_filtered.bam &
bash /home/estorrs/dance/dance/scripts/1.filter_bams.sh /diskmnt/Projects/Users/estorrs/1000-genomes/GRCh37/positions.chr.all.coding.sorted.02maf.10000sampled.sorted.snps.bed /diskmnt/Projects/Users/estorrs/data/ancestry/MM/bams/59114-4.bam /diskmnt/Projects/Users/estorrs/data/ancestry/MM/filtered_bams/59114-4.1000-genome_filtered.bam &
wait
bash /home/estorrs/dance/dance/scripts/1.filter_bams.sh /diskmnt/Projects/Users/estorrs/1000-genomes/GRCh37/positions.chr.all.coding.sorted.02maf.10000sampled.sorted.snps.bed /diskmnt/Projects/Users/estorrs/data/ancestry/MM/bams/59114-N.bam /diskmnt/Projects/Users/estorrs/data/ancestry/MM/filtered_bams/59114-N.1000-genome_filtered.bam &
bash /home/estorrs/dance/dance/scripts/1.filter_bams.sh /diskmnt/Projects/Users/estorrs/1000-genomes/GRCh37/positions.chr.all.coding.sorted.02maf.10000sampled.sorted.snps.bed /diskmnt/Projects/Users/estorrs/data/ancestry/MM/bams/60359-1.bam /diskmnt/Projects/Users/estorrs/data/ancestry/MM/filtered_bams/60359-1.1000-genome_filtered.bam &
bash /home/estorrs/dance/dance/scripts/1.filter_bams.sh /diskmnt/Projects/Users/estorrs/1000-genomes/GRCh37/positions.chr.all.coding.sorted.02maf.10000sampled.sorted.snps.bed /diskmnt/Projects/Users/estorrs/data/ancestry/MM/bams/60359-2.bam /diskmnt/Projects/Users/estorrs/data/ancestry/MM/filtered_bams/60359-2.1000-genome_filtered.bam &
bash /home/estorrs/dance/dance/scripts/1.filter_bams.sh /diskmnt/Projects/Users/estorrs/1000-genomes/GRCh37/positions.chr.all.coding.sorted.02maf.10000sampled.sorted.snps.bed /diskmnt/Projects/Users/estorrs/data/ancestry/MM/bams/60359-N.bam /diskmnt/Projects/Users/estorrs/data/ancestry/MM/filtered_bams/60359-N.1000-genome_filtered.bam &
bash /home/estorrs/dance/dance/scripts/1.filter_bams.sh /diskmnt/Projects/Users/estorrs/1000-genomes/GRCh37/positions.chr.all.coding.sorted.02maf.10000sampled.sorted.snps.bed /diskmnt/Projects/Users/estorrs/data/ancestry/MM/bams/77570-1.bam /diskmnt/Projects/Users/estorrs/data/ancestry/MM/filtered_bams/77570-1.1000-genome_filtered.bam &
bash /home/estorrs/dance/dance/scripts/1.filter_bams.sh /diskmnt/Projects/Users/estorrs/1000-genomes/GRCh37/positions.chr.all.coding.sorted.02maf.10000sampled.sorted.snps.bed /diskmnt/Projects/Users/estorrs/data/ancestry/MM/bams/77570-N.bam /diskmnt/Projects/Users/estorrs/data/ancestry/MM/filtered_bams/77570-N.1000-genome_filtered.bam &
bash /home/estorrs/dance/dance/scripts/1.filter_bams.sh /diskmnt/Projects/Users/estorrs/1000-genomes/GRCh37/positions.chr.all.coding.sorted.02maf.10000sampled.sorted.snps.bed /diskmnt/Projects/Users/estorrs/data/ancestry/MM/bams/83942-1.bam /diskmnt/Projects/Users/estorrs/data/ancestry/MM/filtered_bams/83942-1.1000-genome_filtered.bam &
bash /home/estorrs/dance/dance/scripts/1.filter_bams.sh /diskmnt/Projects/Users/estorrs/1000-genomes/GRCh37/positions.chr.all.coding.sorted.02maf.10000sampled.sorted.snps.bed /diskmnt/Projects/Users/estorrs/data/ancestry/MM/bams/83942-N.bam /diskmnt/Projects/Users/estorrs/data/ancestry/MM/filtered_bams/83942-N.1000-genome_filtered.bam &
bash /home/estorrs/dance/dance/scripts/1.filter_bams.sh /diskmnt/Projects/Users/estorrs/1000-genomes/GRCh37/positions.chr.all.coding.sorted.02maf.10000sampled.sorted.snps.bed /diskmnt/Projects/Users/estorrs/data/ancestry/MM/bams/98433-1.bam /diskmnt/Projects/Users/estorrs/data/ancestry/MM/filtered_bams/98433-1.1000-genome_filtered.bam &
wait
bash /home/estorrs/dance/dance/scripts/1.filter_bams.sh /diskmnt/Projects/Users/estorrs/1000-genomes/GRCh37/positions.chr.all.coding.sorted.02maf.10000sampled.sorted.snps.bed /diskmnt/Projects/Users/estorrs/data/ancestry/MM/bams/37692-2.bam /diskmnt/Projects/Users/estorrs/data/ancestry/MM/filtered_bams/37692-2.1000-genome_filtered.bam &
bash /home/estorrs/dance/dance/scripts/1.filter_bams.sh /diskmnt/Projects/Users/estorrs/1000-genomes/GRCh37/positions.chr.all.coding.sorted.02maf.10000sampled.sorted.snps.bed /diskmnt/Projects/Users/estorrs/data/ancestry/MM/bams/37692-N.bam /diskmnt/Projects/Users/estorrs/data/ancestry/MM/filtered_bams/37692-N.1000-genome_filtered.bam &
bash /home/estorrs/dance/dance/scripts/1.filter_bams.sh /diskmnt/Projects/Users/estorrs/1000-genomes/GRCh37/positions.chr.all.coding.sorted.02maf.10000sampled.sorted.snps.bed /diskmnt/Projects/Users/estorrs/data/ancestry/MM/bams/47499-dna.bam /diskmnt/Projects/Users/estorrs/data/ancestry/MM/filtered_bams/47499-dna.1000-genome_filtered.bam &
