#!/bin/bash

GENOMES_POSITIONS=$1
INPUT_BAM_FP=$2
OUTPUT_READCOUNT_FP=$3
FASTA=$4


samtools index $INPUT_BAM_FP
bam-readcount -w 1 -f $FASTA -l $GENOMES_POSITIONS $INPUT_BAM_FP > $OUTPUT_READCOUNT_FP
