bash /home/estorrs/dance/dance/scripts/2.bam_readcounts.sh /diskmnt/Projects/Users/estorrs/1000-genomes/GRCh37/positions.chr.all.coding.sorted.02maf.10000sampled.sorted.snps.bed /diskmnt/Projects/Users/estorrs/data/ancestry/MM/filtered_bams/25183-dna.1000-genome_filtered.bam /diskmnt/Projects/Users/estorrs/data/ancestry/MM/readcounts/25183-dna.1000-genome_filtered.readcount /diskmnt/Datasets/Reference/LongRanger/GRCh37/refdata-hg19-2.1.0/fasta/genome.fa &
bash /home/estorrs/dance/dance/scripts/2.bam_readcounts.sh /diskmnt/Projects/Users/estorrs/1000-genomes/GRCh37/positions.chr.all.coding.sorted.02maf.10000sampled.sorted.snps.bed /diskmnt/Projects/Users/estorrs/data/ancestry/MM/filtered_bams/27522-1.1000-genome_filtered.bam /diskmnt/Projects/Users/estorrs/data/ancestry/MM/readcounts/27522-1.1000-genome_filtered.readcount /diskmnt/Datasets/Reference/LongRanger/GRCh37/refdata-hg19-2.1.0/fasta/genome.fa &
bash /home/estorrs/dance/dance/scripts/2.bam_readcounts.sh /diskmnt/Projects/Users/estorrs/1000-genomes/GRCh37/positions.chr.all.coding.sorted.02maf.10000sampled.sorted.snps.bed /diskmnt/Projects/Users/estorrs/data/ancestry/MM/filtered_bams/27522-2.1000-genome_filtered.bam /diskmnt/Projects/Users/estorrs/data/ancestry/MM/readcounts/27522-2.1000-genome_filtered.readcount /diskmnt/Datasets/Reference/LongRanger/GRCh37/refdata-hg19-2.1.0/fasta/genome.fa &
bash /home/estorrs/dance/dance/scripts/2.bam_readcounts.sh /diskmnt/Projects/Users/estorrs/1000-genomes/GRCh37/positions.chr.all.coding.sorted.02maf.10000sampled.sorted.snps.bed /diskmnt/Projects/Users/estorrs/data/ancestry/MM/filtered_bams/27522-3.1000-genome_filtered.bam /diskmnt/Projects/Users/estorrs/data/ancestry/MM/readcounts/27522-3.1000-genome_filtered.readcount /diskmnt/Datasets/Reference/LongRanger/GRCh37/refdata-hg19-2.1.0/fasta/genome.fa &
bash /home/estorrs/dance/dance/scripts/2.bam_readcounts.sh /diskmnt/Projects/Users/estorrs/1000-genomes/GRCh37/positions.chr.all.coding.sorted.02maf.10000sampled.sorted.snps.bed /diskmnt/Projects/Users/estorrs/data/ancestry/MM/filtered_bams/27522-N.1000-genome_filtered.bam /diskmnt/Projects/Users/estorrs/data/ancestry/MM/readcounts/27522-N.1000-genome_filtered.readcount /diskmnt/Datasets/Reference/LongRanger/GRCh37/refdata-hg19-2.1.0/fasta/genome.fa &
wait
bash /home/estorrs/dance/dance/scripts/2.bam_readcounts.sh /diskmnt/Projects/Users/estorrs/1000-genomes/GRCh37/positions.chr.all.coding.sorted.02maf.10000sampled.sorted.snps.bed /diskmnt/Projects/Users/estorrs/data/ancestry/MM/filtered_bams/37692-1.1000-genome_filtered.bam /diskmnt/Projects/Users/estorrs/data/ancestry/MM/readcounts/37692-1.1000-genome_filtered.readcount /diskmnt/Datasets/Reference/LongRanger/GRCh37/refdata-hg19-2.1.0/fasta/genome.fa &
bash /home/estorrs/dance/dance/scripts/2.bam_readcounts.sh /diskmnt/Projects/Users/estorrs/1000-genomes/GRCh37/positions.chr.all.coding.sorted.02maf.10000sampled.sorted.snps.bed /diskmnt/Projects/Users/estorrs/data/ancestry/MM/filtered_bams/56203-1.1000-genome_filtered.bam /diskmnt/Projects/Users/estorrs/data/ancestry/MM/readcounts/56203-1.1000-genome_filtered.readcount /diskmnt/Datasets/Reference/LongRanger/GRCh37/refdata-hg19-2.1.0/fasta/genome.fa &
bash /home/estorrs/dance/dance/scripts/2.bam_readcounts.sh /diskmnt/Projects/Users/estorrs/1000-genomes/GRCh37/positions.chr.all.coding.sorted.02maf.10000sampled.sorted.snps.bed /diskmnt/Projects/Users/estorrs/data/ancestry/MM/filtered_bams/56203-2.1000-genome_filtered.bam /diskmnt/Projects/Users/estorrs/data/ancestry/MM/readcounts/56203-2.1000-genome_filtered.readcount /diskmnt/Datasets/Reference/LongRanger/GRCh37/refdata-hg19-2.1.0/fasta/genome.fa &
bash /home/estorrs/dance/dance/scripts/2.bam_readcounts.sh /diskmnt/Projects/Users/estorrs/1000-genomes/GRCh37/positions.chr.all.coding.sorted.02maf.10000sampled.sorted.snps.bed /diskmnt/Projects/Users/estorrs/data/ancestry/MM/filtered_bams/56203-N.1000-genome_filtered.bam /diskmnt/Projects/Users/estorrs/data/ancestry/MM/readcounts/56203-N.1000-genome_filtered.readcount /diskmnt/Datasets/Reference/LongRanger/GRCh37/refdata-hg19-2.1.0/fasta/genome.fa &
bash /home/estorrs/dance/dance/scripts/2.bam_readcounts.sh /diskmnt/Projects/Users/estorrs/1000-genomes/GRCh37/positions.chr.all.coding.sorted.02maf.10000sampled.sorted.snps.bed /diskmnt/Projects/Users/estorrs/data/ancestry/MM/filtered_bams/58408-1.1000-genome_filtered.bam /diskmnt/Projects/Users/estorrs/data/ancestry/MM/readcounts/58408-1.1000-genome_filtered.readcount /diskmnt/Datasets/Reference/LongRanger/GRCh37/refdata-hg19-2.1.0/fasta/genome.fa &
wait
bash /home/estorrs/dance/dance/scripts/2.bam_readcounts.sh /diskmnt/Projects/Users/estorrs/1000-genomes/GRCh37/positions.chr.all.coding.sorted.02maf.10000sampled.sorted.snps.bed /diskmnt/Projects/Users/estorrs/data/ancestry/MM/filtered_bams/58408-2.1000-genome_filtered.bam /diskmnt/Projects/Users/estorrs/data/ancestry/MM/readcounts/58408-2.1000-genome_filtered.readcount /diskmnt/Datasets/Reference/LongRanger/GRCh37/refdata-hg19-2.1.0/fasta/genome.fa &
bash /home/estorrs/dance/dance/scripts/2.bam_readcounts.sh /diskmnt/Projects/Users/estorrs/1000-genomes/GRCh37/positions.chr.all.coding.sorted.02maf.10000sampled.sorted.snps.bed /diskmnt/Projects/Users/estorrs/data/ancestry/MM/filtered_bams/58408-N.1000-genome_filtered.bam /diskmnt/Projects/Users/estorrs/data/ancestry/MM/readcounts/58408-N.1000-genome_filtered.readcount /diskmnt/Datasets/Reference/LongRanger/GRCh37/refdata-hg19-2.1.0/fasta/genome.fa &
bash /home/estorrs/dance/dance/scripts/2.bam_readcounts.sh /diskmnt/Projects/Users/estorrs/1000-genomes/GRCh37/positions.chr.all.coding.sorted.02maf.10000sampled.sorted.snps.bed /diskmnt/Projects/Users/estorrs/data/ancestry/MM/filtered_bams/59114-2.1000-genome_filtered.bam /diskmnt/Projects/Users/estorrs/data/ancestry/MM/readcounts/59114-2.1000-genome_filtered.readcount /diskmnt/Datasets/Reference/LongRanger/GRCh37/refdata-hg19-2.1.0/fasta/genome.fa &
bash /home/estorrs/dance/dance/scripts/2.bam_readcounts.sh /diskmnt/Projects/Users/estorrs/1000-genomes/GRCh37/positions.chr.all.coding.sorted.02maf.10000sampled.sorted.snps.bed /diskmnt/Projects/Users/estorrs/data/ancestry/MM/filtered_bams/59114-3.1000-genome_filtered.bam /diskmnt/Projects/Users/estorrs/data/ancestry/MM/readcounts/59114-3.1000-genome_filtered.readcount /diskmnt/Datasets/Reference/LongRanger/GRCh37/refdata-hg19-2.1.0/fasta/genome.fa &
bash /home/estorrs/dance/dance/scripts/2.bam_readcounts.sh /diskmnt/Projects/Users/estorrs/1000-genomes/GRCh37/positions.chr.all.coding.sorted.02maf.10000sampled.sorted.snps.bed /diskmnt/Projects/Users/estorrs/data/ancestry/MM/filtered_bams/59114-4.1000-genome_filtered.bam /diskmnt/Projects/Users/estorrs/data/ancestry/MM/readcounts/59114-4.1000-genome_filtered.readcount /diskmnt/Datasets/Reference/LongRanger/GRCh37/refdata-hg19-2.1.0/fasta/genome.fa &
wait
bash /home/estorrs/dance/dance/scripts/2.bam_readcounts.sh /diskmnt/Projects/Users/estorrs/1000-genomes/GRCh37/positions.chr.all.coding.sorted.02maf.10000sampled.sorted.snps.bed /diskmnt/Projects/Users/estorrs/data/ancestry/MM/filtered_bams/59114-N.1000-genome_filtered.bam /diskmnt/Projects/Users/estorrs/data/ancestry/MM/readcounts/59114-N.1000-genome_filtered.readcount /diskmnt/Datasets/Reference/LongRanger/GRCh37/refdata-hg19-2.1.0/fasta/genome.fa &
bash /home/estorrs/dance/dance/scripts/2.bam_readcounts.sh /diskmnt/Projects/Users/estorrs/1000-genomes/GRCh37/positions.chr.all.coding.sorted.02maf.10000sampled.sorted.snps.bed /diskmnt/Projects/Users/estorrs/data/ancestry/MM/filtered_bams/60359-1.1000-genome_filtered.bam /diskmnt/Projects/Users/estorrs/data/ancestry/MM/readcounts/60359-1.1000-genome_filtered.readcount /diskmnt/Datasets/Reference/LongRanger/GRCh37/refdata-hg19-2.1.0/fasta/genome.fa &
bash /home/estorrs/dance/dance/scripts/2.bam_readcounts.sh /diskmnt/Projects/Users/estorrs/1000-genomes/GRCh37/positions.chr.all.coding.sorted.02maf.10000sampled.sorted.snps.bed /diskmnt/Projects/Users/estorrs/data/ancestry/MM/filtered_bams/60359-2.1000-genome_filtered.bam /diskmnt/Projects/Users/estorrs/data/ancestry/MM/readcounts/60359-2.1000-genome_filtered.readcount /diskmnt/Datasets/Reference/LongRanger/GRCh37/refdata-hg19-2.1.0/fasta/genome.fa &
bash /home/estorrs/dance/dance/scripts/2.bam_readcounts.sh /diskmnt/Projects/Users/estorrs/1000-genomes/GRCh37/positions.chr.all.coding.sorted.02maf.10000sampled.sorted.snps.bed /diskmnt/Projects/Users/estorrs/data/ancestry/MM/filtered_bams/60359-N.1000-genome_filtered.bam /diskmnt/Projects/Users/estorrs/data/ancestry/MM/readcounts/60359-N.1000-genome_filtered.readcount /diskmnt/Datasets/Reference/LongRanger/GRCh37/refdata-hg19-2.1.0/fasta/genome.fa &
bash /home/estorrs/dance/dance/scripts/2.bam_readcounts.sh /diskmnt/Projects/Users/estorrs/1000-genomes/GRCh37/positions.chr.all.coding.sorted.02maf.10000sampled.sorted.snps.bed /diskmnt/Projects/Users/estorrs/data/ancestry/MM/filtered_bams/77570-1.1000-genome_filtered.bam /diskmnt/Projects/Users/estorrs/data/ancestry/MM/readcounts/77570-1.1000-genome_filtered.readcount /diskmnt/Datasets/Reference/LongRanger/GRCh37/refdata-hg19-2.1.0/fasta/genome.fa &
wait
bash /home/estorrs/dance/dance/scripts/2.bam_readcounts.sh /diskmnt/Projects/Users/estorrs/1000-genomes/GRCh37/positions.chr.all.coding.sorted.02maf.10000sampled.sorted.snps.bed /diskmnt/Projects/Users/estorrs/data/ancestry/MM/filtered_bams/77570-N.1000-genome_filtered.bam /diskmnt/Projects/Users/estorrs/data/ancestry/MM/readcounts/77570-N.1000-genome_filtered.readcount /diskmnt/Datasets/Reference/LongRanger/GRCh37/refdata-hg19-2.1.0/fasta/genome.fa &
bash /home/estorrs/dance/dance/scripts/2.bam_readcounts.sh /diskmnt/Projects/Users/estorrs/1000-genomes/GRCh37/positions.chr.all.coding.sorted.02maf.10000sampled.sorted.snps.bed /diskmnt/Projects/Users/estorrs/data/ancestry/MM/filtered_bams/83942-1.1000-genome_filtered.bam /diskmnt/Projects/Users/estorrs/data/ancestry/MM/readcounts/83942-1.1000-genome_filtered.readcount /diskmnt/Datasets/Reference/LongRanger/GRCh37/refdata-hg19-2.1.0/fasta/genome.fa &
bash /home/estorrs/dance/dance/scripts/2.bam_readcounts.sh /diskmnt/Projects/Users/estorrs/1000-genomes/GRCh37/positions.chr.all.coding.sorted.02maf.10000sampled.sorted.snps.bed /diskmnt/Projects/Users/estorrs/data/ancestry/MM/filtered_bams/83942-N.1000-genome_filtered.bam /diskmnt/Projects/Users/estorrs/data/ancestry/MM/readcounts/83942-N.1000-genome_filtered.readcount /diskmnt/Datasets/Reference/LongRanger/GRCh37/refdata-hg19-2.1.0/fasta/genome.fa &
bash /home/estorrs/dance/dance/scripts/2.bam_readcounts.sh /diskmnt/Projects/Users/estorrs/1000-genomes/GRCh37/positions.chr.all.coding.sorted.02maf.10000sampled.sorted.snps.bed /diskmnt/Projects/Users/estorrs/data/ancestry/MM/filtered_bams/98433-1.1000-genome_filtered.bam /diskmnt/Projects/Users/estorrs/data/ancestry/MM/readcounts/98433-1.1000-genome_filtered.readcount /diskmnt/Datasets/Reference/LongRanger/GRCh37/refdata-hg19-2.1.0/fasta/genome.fa &
